"""appointment awaiting reschedule

Revision ID: 0012_appointment_awaiting_reschedule
Revises: 0011_appointment_awaiting_confirmation
Create Date: 2026-05-12 20:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0012_appt_awaiting_reschedule'
down_revision: Union[str, None] = '0011_appt_confirm'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('awaiting_reschedule', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'awaiting_reschedule')
    # ### end Alembic commands ###
